spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/spring_microservices?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Mysql@root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat :
      max-wait : 20000
      max-active : 50
      max-idle : 20
      min-idle : 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

